finos/common-cloud-controls

- Readme.md
Two typos under #lLicense section:
- Fixes spacing between word and punctuation.
- Removes "is" from "The source code is included in this repository is subject to the [Apache-2.0 License".
> Fix typo and spacing in README.md

- Readme.md
This PR adds @pgste from Morgan Stanley to the `Define Cloud Services Taxonomy` and `OSCAL Representation of CCC` working groups in the FINOS CCC project `ReadMe.md`
> Update Paul Stevenson from Morgan Stanley to ReadMe.md

- docs/governance/working-groups/delivery/charter.md
Collaborating on this with @eddie-knight, @mlysaght2017, and @robmoffat.
Part of #171
> Initial Draft of the Delivery WG Charter

- docs/governance/community-guidelines/communication.md
Add a  note to remind people that if adjusting/cancelling a FINOS hosted meeting that people should include a FINOS employee when making the changes.
> Add a warning on changing FINOS hosted meetings

- docs/governance/working-groups/taxonomy/charter.md
Fix the link to the delivery working group in the taxonomy working groups charter.
> Fix link to delivery wg in taxonomy charter

- .github/workflows/stale_meeting.yml
Addresses issue https://github.com/finos/common-cloud-controls/issues/231
Add a new workflow rule which will close issues labeled "meeting" after 14 days of inactivity.
> New workflow to close issues tagged with "meeting" after 14 days.

- .github/workflows/links.yml
- .github/workflows/pr_workflow.yaml
- .github/workflows/stale_meeting.yml
Add [lychee](https://github.com/lycheeverse/lychee-action) as a link checker.
Standardise on kebab case for job names
> Add lychee as a link checker.

- .github/CODEOWNERS
I'm still not sure that our teams have the correct permissions, but I'm hoping this makes the directory ownership work.
> Minor fixes to the CODEOWNERS file

- services/storage/object/controls.md
Need to work on tests, but would like to get to initial feedback on control objectives first
> Add in new object storage controls on encryption for impact and replication to untrusted destinations

- docs/governance/community-guidelines/templates/schemas/README.md
- docs/governance/community-guidelines/templates/schemas/controls-schema.json
- docs/governance/community-guidelines/templates/schemas/features-schema.json
- docs/governance/community-guidelines/templates/schemas/metadata-schema.json
- docs/governance/community-guidelines/templates/schemas/threats-schema.json
Add YAML schemas for controls, features, metadata and threats. Tested locally with VSCode
Using draft-07 as it seems most widely supported
> Add yaml schemas (Issue #364)

- .gitvote.yml
Increase the vote duration form 5 days to 7 days to ensure we give a full working week to vote (ignoring any holidays).
Remove the daily status check as it was causing confusion and noise on the PRs.
> Increase the vote duration to 7 days and remove the status check

- schemas/controls-schema.json
this changes the test_requirements object to have TLP level associated with each requirement, instead of the other way around (which resulted in repetition of test requirements)
**previous**:
```yaml
test_requirements:
tlp_green:
01: |
Simulate non-human enumeration activities (e.g., with service accounts) and verify that alerts are triggered in the logging system.
02: |
Confirm that logs are properly generated and accessible for review following non-human enumeration attempts.
tlp_amber:
01: |
Simulate non-human enumeration activities (e.g., with service accounts) and verify that alerts are triggered in the logging system.
02: |
Confirm that logs are properly generated and accessible for review following non-human enumeration attempts.
```
**updated**:
```yaml
test_requirements:
- id: …
```
> Adjusted test_requirements format

- services/database/warehouse/controls.yaml
in collaboration with @nas-hub
> New controls.yaml for Database/Warehouse

- services/compute/serverless-computing/controls.yaml
controls for Cloud functions - in Collab with @nas-hub
> New controls.yaml for Compute/Serverless

- .github/workflows/sonatype_scan.yaml
Updated the workflow trigger event to use 'pull_request_target' instead of 'pull_request'. This allows workflows to run with access to secrets and environment variables in the context of the base (target) branch.
> Change GitHub Actions trigger from pull_request to pull_request_target

- services/database/relational/controls.yaml
- services/database/relational/threats.yaml
Adding rdms controls 
Adding 1x control
Creation of the controls.yaml file
> Creation of initial RDMS controls.yaml file

- services/devtools/build/features.yaml
For services such as GCP codebuild, AWS codebuild, and Azure DevOps
> Create features.yaml for devtools/build

- .github/workflows/pr-title.yaml
> feat(ci): Add pr-title workflow

- docs/community-guidelines/guidelines-to-policies.md
Adjust guideline to policy to include more specifics about the voting procedure.
> change(docs): Adjust guideline to policy to include more specifics about the voting procedure.

- services/storage/object/controls.yaml
This pull request includes updates to the `controls.yaml` file in the `services/storage/object` directory.
Key changes include:
* Updated `control_mappings` for threats CCC.TH06, CCC.TH07 and CCC.TH09:
* Added mappings for `CCM`, `ISO_27001`, and `NIST_800_53` standards.
> change(control): add in missing controls mappings for object storage

- services/common-controls.yaml
Added missing mappings to NIST controls for common controls. Does not include CCM/ISO mappings
> Added missing mappings to NIST controls

- services/database/relational/features.yaml
- services/database/relational/threats.yaml
Made the following amendments 
- Added missing common feature to feature list
- Amended ID ordering
- Removed duplicated threats
- Added new common threats to RDMS
> Threats reviewed and amended for RDMS

- services/crypto/key/controls.yaml
- services/crypto/key/features.yaml
- services/crypto/key/threats.yaml
- Added features for Key Expiry, Regionality, Replication, Usage Limits, Permissions, Export
- Added common threat CCC.TH04 and common control CCC.C10
> Prepare crypto/key for release candidate

- docs/resources/frameworks/three-tier-app.md
So that we can reference this via a dedicated doc...
I think we really do need to implement this reference architecture for at least one cloud provider—preferably all three—to ensure that we are capturing the right set of foundational services and configuration patterns. 
While the [Google Cloud reference document](https://cloud.google.com/architecture/single-zone-deployment-compute-engine) scopes this architecture to a small set of services (primarily four), I reckon that limiting ourselves to a theoretical mapping of just 4 services will leave us with a pretty big validation gap. This feels like a good early opportunity to do that validation. 
You'll see in the table that I've added additional Sec/Mangement/Obs/Crypto services that I believe the community would be expecting to be in …
> Add in service mappings for three tier app

- delivery-toolkit/cmd/gen-oscal.go
- delivery-toolkit/sample-artifacts/CCC.ObjStor_2025.09.oscal.json
This PR updates the `delivery-toolkit` OSCAL generation to include the top-level `catalog` key in the final OSCAL catalog artifact to ensure it can be validated against the OSCAL JSON schema.
The sample artifact was regenerated by running:
`go run . generate-release-artifacts --build-target "storage/object`
When validating the sample artifact in `main`, this error is thrown:
`expected model to have 1 key, got 3`
> fix(ci): updates OSCAL generation to include top-level key

- catalogs/core/ccc/controls.yaml
This adds mappings to CCMv4, removing references to CCMv3 (v4 contains internal references to v3).
Note that this does not include an update to add the mapping reference data in `metadata.yaml`, which can be taken care of later all at once before we cut the release.
> change(control): Update CSA CCM mappings in CCC.Core

- catalogs/core/ccc/threats.yaml
Our threats are always treated as fully applicable to their capabilities, so we don't need to use the optional `strength` field in the capability mappings.
Non-functional change.
> change(threat): Remove unecessary strength in threat->capability mappings

- catalogs/core/ccc/capabilities.yaml
- catalogs/core/ccc/threats.yaml
This capability is for any service that takes inputs while running (pretty much everything).
If it takes input, there's a chance it could be spammed and DOS the service or system or network.
> add(threat): Added capability and threat for Active Ingestion
