- services/common-cloud-services.md
- services/database/relational/rdms-taxonomy.feature
- services/database/relational/taxonomy.md
This will resolve the need outlined in #48 
Considering the progress made by the group recently, I believe it's time for us to get an early iteration of the outputs. While the output formats are _absolutely_ still subject to change, I hope this can help get the ball rolling to streamline future efforts being made by the group.
1. Migrated suggestions from @smendis-scottlogic, @AdrianHammond and others into `services/database/relational/taxonomy.md`.
2. Separate from (but inspired by) @rowan-baker's work, I took a stab at creating a gherkin feature file with a scenario for each taxonomy feature.
3. Took a stab at what this might look like if we were to compile everything into a single output doc: `services/common-cloud-services.md`. I _did not_ attempt to fully metabolize all of the …
> RDMS Taxonomy

- participants.md
My name is Rowan Baker, and I'd like to formally participate to the Finos Common Cloud Controls project.
By making contribution to this repository, I agree to the terms of the following documents located at: https://github.com/finos/standards-project-blueprint:
(a) Community Specification License 1.0 (.0_Community_Specification_License-v1.md)
(b) Community Specification Governance Policy 1.0 (5._Governance.md)
(c) Community Specification Contribution Policy 1.0 (6._Contributing.md)
(d) Community Specification Code of Conduct (8._Code_of_Conduct.md)
In addition, for source code contributions, I certify that:
(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or (b) The contribution is based upon …
> Update participants.md with Rowan Baker, ControlPlane

- participants.md
My name is Vicente Herrera Garcia, and I'd like to formally participate to the Finos Common Cloud Controls project.
By making contribution to this repository, I agree to the terms of the following documents located at: https://github.com/finos/standards-project-blueprint:
(a) Community Specification License 1.0 (.0_Community_Specification_License-v1.md)
(b) Community Specification Governance Policy 1.0 (5._Governance.md)
(c) Community Specification Contribution Policy 1.0 (6._Contributing.md)
(d) Community Specification Code of Conduct (8._Code_of_Conduct.md)
In addition, for source code contributions, I certify that:
(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or (b) The contribution is …
> Update participants.md - Vicente Herrera Garcia - Control Plane

- Readme.md
Updated the doc to reflect support of OSCAL and MITRE workstreams
> Updating readme

- participants.md
My name is Henry Mortimer, and I'd like to formally participate to the Finos Common Cloud Controls project.
By making contribution to this repository, I agree to the terms of the following documents located at: https://github.com/finos/standards-project-blueprint:
(a) Community Specification License 1.0 (.0_Community_Specification_License-v1.md)
(b) Community Specification Governance Policy 1.0 (5._Governance.md)
(c) Community Specification Contribution Policy 1.0 (6._Contributing.md)
(d) Community Specification Code of Conduct (8._Code_of_Conduct.md)
In addition, for source code contributions, I certify that:
(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or (b) The contribution is based …
> Add Henry as participant

- .gitignore
- build/Makefile
- src/oscal/Readme.md
- src/oscal/examples/catalog/json/OSCAL_CCC_Catalog_option1.json
- src/oscal/examples/catalog/json/OSCAL_CCC_Catalog_option2.json
- src/oscal/examples/catalog/xml/OSCAL_CCC_Catalog_option1.xml
- src/oscal/examples/catalog/xml/OSCAL_CCC_Catalog_option2.xml
- src/oscal/examples/catalog/yaml/OSCAL_CCC_Catalog_option1.yaml
- src/oscal/examples/catalog/yaml/OSCAL_CCC_Catalog_option2.yaml
The PR is providing examples directory and catalog examples are as follows:
- [examples](./examples): This directory contains sample OSCAL content organized by OSCAL models. 
- [examples/catalog](./examples/catalog): This directory contains sample OSCAL content organized by OSCAL models.
- [examples/catalog/xml](./examples/catalog/xml): XML representations of the OSCAL CCC catalog examples.
- [examples/catalog/json](./examples/catalog/json): JSON representations of the OSCAL CCC catalog examples.
- [examples/catalog/yaml](./examples/catalog/yaml): YAML representations of the OSCAL CCC catalog examples.
Additionally, a Makefile that installs locally the `oscal-cli` tool for content reformatting and validation.
> PR provides OSCAL catalog examples and validation approach with oscal-cli .

- participants.md
Adding my name to the list of participants for CCC
> updating participants.md

- docs/governance/steering/charter.md
Fix header level of FINOS Point of Contact in Steer Co Charter
> Fix header level of FINOS Point of Contact in Steer Co Charter

- docs/governance/community-groups.md
- docs/governance/working-groups/community-structure/charter.md
Collaboration with @sshiells-scottlogic
> Initial charter draft for Community Structure WG

- docs/governance/working-groups/communications/charter.md
Drafted in collaboration with @Alexstpierrework incorporating input from @jared-lambert and @caradelia.
Part of #171
> First draft of comms wg charter

- participants.md
Added Ted Newman from NatWest Group to participants.md
> Update participants.md -TN

- .github/ISSUE_TEMPLATE/minutes_all-hands-comms.md
- .github/ISSUE_TEMPLATE/minutes_community-structure.md
- .github/ISSUE_TEMPLATE/minutes_delivery.md
- .github/ISSUE_TEMPLATE/minutes_duplication-reduction.md
- .github/ISSUE_TEMPLATE/minutes_security.md
- .github/ISSUE_TEMPLATE/minutes_taxonomy.md
- Change headers to match WG instead of "All Hands"
- Add regular times to save WG leads having to fill out - use language to indicate that these are the standard times
> Review and update WG meeting issue templates

- .github/CODEOWNERS
Blocks #263 
Duplicate of #294
> Added Security WG codeowners for *.feature

- docs/resources/readme.md
simple description of CDMC. plan to add a better one in the near future which will include links to docs & training material
> Update readme.md to mention CDMC in the controls section

- services/storage/object/controls.md
Added CCC.OS.C6: Prevent access to object storage from trusted cloud tenants and cloud services
> Added CCC.OS.C6 Control

- docs/resources/frameworks/cncf_cloud_native_control_catalog.md
Addresses #199 
As discussed, focused only on a review of the CNCF control catalog along with recommendations
> Add in resource doc on CNCF cloud native control catalog

- docs/governance/community-guidelines/releases.md
- docs/governance/community-guidelines/versioning.md
- docs/resources/readme.md
This PR contains a new document that contains the guidelines for how we go about versioning our artifacts. This was derived from our discussion: #268
Let me know if you have any questions, comments, or concerns.
> Versioning Guidelines

- docs/governance/community-guidelines/content-standards-and-practices/assurance-level-definitions.md
> Assurance Level Definitions

- docs/.gitvote.yml
Add intial gitvote config with some best guess parameters for what we want:
Vote duration: 5 days
Periodic automatic status check: 1 day
Pass Threshold: 50% (i.e. majority)
Vote closes on passing: true
Binding votes: SteerCo
> Add initial gitvote config

- .gitvote.yml
Update vote pass threshold to 51 percent to ensure it requires a majority in case of an even number of voters
> Update vote pass threshold to 51 percent

- docs/governance/community-guidelines/content-standards-and-practices/feature-definitions.md
- docs/governance/community-guidelines/content-standards-and-practices/identifiers.md
- docs/governance/community-guidelines/content-standards-and-practices/release-assets.md
- docs/governance/community-guidelines/content-standards-and-practices/threat-definitions.md
- services/common-features.yaml
- services/crypto/key/metadata.yaml
- services/crypto/service-families.yaml
- services/service-families.yaml
This PR will contain necessary base files for the KMS work to build upon.
> Update to common features and service families

- services/crypto/key/features.yaml
Add initial `features.yaml` for the Key Management Service (#323)
> Add Key Management Service to CCC service taxonomy (#323)

- docs/governance/community-guidelines/content-standards-and-practices/control-definitions.md
- docs/governance/community-guidelines/content-standards-and-practices/threat-definitions.md
- docs/governance/community-guidelines/templates/schemas/controls-schema.json
- docs/governance/community-guidelines/templates/schemas/threats-schema.json
Drafted in collaboration with @damienjburks and @mlysaght2017
> Updating to use techniques—not tactics— in threats— not controls.

- docs/governance/community-guidelines/templates/controls.yaml
- docs/governance/community-guidelines/templates/schemas/controls-schema.json
@eddie-knight - separated out minor control schema and template updates
> Update controls schema and template to remove mapping and mitre ttp

- .github/CODEOWNERS
Changes should fix the following:
https://github.com/finos/common-cloud-controls/pull/412
#409
> updating codeowners file to fix Broken PRs

- services/common-features.yaml
Mostly style changes, and a new common feature
> Updated common features

- services/common-threats.yaml
Several changes to common threats pulled in from my other _WIP_ PRs. These common items have bubbled up while I've been working sporadically on GenAI, MLDE, and ObjStor.
I've also included a swath of formatting and style changes.
> Updated common threats

- docs/governance/community-guidelines/releases.md
New section in the release guidelines that includes more information about the release candidate preparation and validation process. This is the first iteration; I am certain that it will be updated as we mature our process.
> Updating Release Process - Release Candidate Preparation

- .vscode/controls.code-snippets
- docs/governance/community-guidelines/templates/controls.yaml
- docs/governance/community-guidelines/templates/threats.yaml
Update the controls snippet and the threats example files to match recent changes to the schema.
> Update controls snippet and controls and threats example files

- services/common-controls.yaml
- services/common-features.yaml
- services/common-threats.yaml
- reorganized threats and assigned new IDs (destructive, but created some more intuitive sorting for these early additions)
- added title comments to ID lines, for easier readability while working (ie, folded sections in VSCode) and easier copying to other files later.
- corrected line lengths
- added test requirements
- started adding control mappings, but paused on that for now 
follows #420
> Refactoring common entries

- services/ai-ml/gen-ai/features.yaml
- services/crypto/key/features.yaml
- services/networking/loadbalancer/features.yaml
Incorporating the changes from #418 into existing features files
> Reformatting service category features

- .vscode/common-features.code-snippets
- .vscode/common-threats.code-snippets
- .vscode/controls.code-snippets
Add common features and threat snippets to help ease and speed up development.
Common control snippets and instructions on how to use are to follow in a separate PR.
As a quick start if you type "CF" or "CT" in vscode suggestions for complete show up.
> Add common features and threats snippets

- .vscode/common-controls.code-snippets
- docs/development.md
- Add common controls snippets for VSCode
- Add some supporting documentation (Note: Note sure where best to put this so I've added to `/docs` for now but can move as required.
> Issue 438: Add Common Controls Snippets

- services/ai-ml/gen-ai/features.yaml
Added plugin integration to GenAI features. As discussed in NYC workshop session on Sept 30th with Andy, Eddie et al.
> Added GenAI feature: "Plugin Integration"

- services/networking/vpc/features.yaml
> Create features.yaml for VPC

- services/database/warehouse/threats.yaml
in collaboration with @nas-hub
> New threats.yaml for Database/Warehouse

- .github/workflows/sonatype_scan.yaml
The Sonatype Platform is scanning for open source dependencies, providing security and license details, and checking in a SPDX SBOM as a build artifact.
> Create sonatype_scan.yaml to scan for OSS

- services/crypto/secMgmt/features.yaml
Still need to add References if needed
> Create features.yaml for SecMgmt

- services/storage/object/controls.yaml
> Add in updates to soft and hard delete bucket controls

- services/networking/service-categories.yaml
- services/networking/vpc/features.yaml
- services/networking/vpc/metadata.yaml
This is an enhanced version of features supported by service providers for VPC
> Detailed feature list for VPC

- services/compute/serverless-computing/threats.yaml
threats.yaml for cloud functions
> New threats.yaml for Compute/Serverless

- services/app-integration/message/threats.yaml
> New threats.yaml for AppIntegration/Message

- services/app-integration/message/controls.yaml
> Created/Updated controls.yaml for AppIntegration/Message

- services/common-controls.yaml
Added control for Key management
> Update common-controls.yaml to add key management policy

- delivery-tooling/catalog-compiler.go
- delivery-tooling/templates/catalog.md
Add links links to the table of the release markdown
> Add links to release markdown

- docs/community-guidelines/content-standards-and-practices/threat-definitions.md
@eddie-knight @damienjburks - trying to add more style guidance for threats to improve consistency.
> Update Threat Definition Guidelines 

- .github/workflows/pr-title.yaml
This PR applies the following PR title options:
For proposed additions to the repo:
- add(ci):
- add(docs):
- add(feature):
- add(threat):
- add(control):
- add(category):
- add(family):
For proposed changes to the repo:
- change(ci):
- change(docs):
- change(feature):
- change(threat):
- change(control):
- change(category):
- change(family):
For proposed removals from the repo:
- remove(ci):
- remove(docs):
- remove(feature):
- remove(threat):
- remove(control):
- remove(category):
- remove(family):
<details><summary>Click to show the previous options for PR titles</summary>
-----
- ci(add):
- ci(category):
- ci(change):
- ci(controls):
- ci(family):
- ci(remove):
- ci(threats):
-----
- docs(add):
- docs(category):
- docs(change):
- docs(controls):
- docs(family):
- docs(remove):
- …
> docs(change): changed PR Title requirements

- participants.md
My name is Gordon Campbell, and as part of Scott Logic, will be contributing to the Common Cloud Controls project.
> change(docs): Add new participant: Gordon Campbell

- services/ai-ml/mlde/features.yaml
This PR includes updates to the `features.yaml` file in the `services/ai-ml/mlde` directory.
The key changes include:
1. Addition of common features:
- API Access (CCC.F14) - Essential for programmatic interaction with the ML environment
- Cost Management (CCC.F15) - Critical for ML workloads which can be computationally expensive
- Budgeting (CCC.F16) - Important for controlling ML training costs
- Alerting (CCC.F17) - Necessary for long-running training jobs and resource usage
- Tagging (CCC.F20) - Important for organizing ML projects and resources
- Network Access Rules (CCC.F23) - Critical for securing ML development environments
2.  Addition of specific features:
- CCC.MLDE.F06 - GPU/Specialized Hardware Support - Provides access to GPU instances and specialized ML acceleration …
> change(feature): Adding additional common and specific features for MLDE

- participants.md
My name is Akin Akinbobola from LSEG and I will do like to formally contribute to the common-cloud-controls project
> add(docs): Add Akin to participants

- .vscode/settings.json
- services/common-threats.yaml
- services/crypto/SecMgmt/threats.yaml
Common threats style alignment to style guide
> Common threats style alignment

- services/identity/iam/metadata.yaml
- services/identity/service-categories.yaml
@fossil-creek This is the placeholder for IAM
@damienjburks, @sshiells-scottlogic Eric needs this to start working on the IAM feature set. Appreciate if you can take a look and approve so that this can be merged to unblock Eric. Thanks!
> Placeholder for IAM feature set

- docs/community-policies/adding-modifying-guidelines.md
- docs/community-policies/guidelines-to-policies.md
Proposal to move the guidelines on adding/modifying guidelines and upgrading a guideline to a policy to become the first community policies.
> change(docs): Upgrade guideline and policy guidelines to become policys

- participants.md
PR for EasyCLA check on CSL signature
> Update participants.md for NatWest Group participants

- docs/community-guidelines/content-standards-and-practices/staging-for-a-release-candidate.md
> add(docs): add in guide on how to prepare threats and controls for release candidate

- docs/community-guidelines/content-standards-and-practices/staging-for-a-release-candidate.md
- docs/community-guidelines/releases/README.md
- docs/resources/frameworks/cncf_cloud_native_control_catalog.md
- docs/resources/training/user_guides/delivery_toolkit.md
- participants.md
> fix(docs): ran prettier across the full repo

- schemas/threats-schema.json
Update threats schema to remove pattern to allow mapping to different frameworks
> change(ci): Update threats schema to remove pattern to allow mapping to different frameworks

- services/management/auditlog/metadata.yaml
> add(docs): Audit Log Metadata

- services/management/auditlog/capabilities.yaml
Added Capabilities of audit logs
> add(capability): Audit Log Capabilities

- services/management/logging/capabilities.yaml
> add(capability): Logging capabilities

- delivery-toolkit/cmd/gen-markdown.go
- delivery-toolkit/cmd/gen-release-notes.go
- delivery-toolkit/cmd/gen-yaml.go
- delivery-toolkit/cmd/generate-release-artifacts.go
- delivery-toolkit/sample-artifacts/release-details.yaml
thanks @robmoffat for catching this bug
> fix(ci): generate release-details.yaml

- catalogs/core/ccc/controls.yaml
There was not a control for Core.TH06. I think this should cover it well enough.
> add(control): Added Core.C14 to mitigate Core.TH06
